### ISSUE TITLE
SOFT paper reference

### ISSUE THREAD

**Issue by gs14iitbbs** [Mayankm96/Stereo-Odometry-SOFT#1]
Hi @Mayankm96,

First of all thanks for contributing the code as opensource, as it is very helpful for research purposes. 

I want to know if it is complete implementation of SOFT and  were you able to get the same error rates as reported in the SOFT paper ?

Please let me know , its urgent. I am currently implementing in C++. But I could not get the  same results, they differ a lot. And therefore I am referring to your implementation. 

I doubt if they have given less details in the paper, or I am missing something.

Regards
Gaurav

**Comment by Mayankm96** [comment]
Hey, @gs14iitbbs!

Thank you for showing interest in this work. 

> I want to know if it is a complete implementation of SOFT and were you able to get the same error rates as reported in the SOFT paper?

Unfortunately, this isn't the *exact* implementation of the SOFT algorithm. As far as I remember, there were sections in the paper that were unclear to me, at the time I wrote this implementation, due to which I had replaced those parts with similar algorithms on the basis of my understanding and other papers that I had read on visual odometry. This implementation was, moreover, left at a qualitative analysis of the odometry generated, and I didn't get to do a quantitative analysis due to a shortage of time.


> Please let me know, it's urgent. I am currently implementing in C++. But I could not get the same results, they differ a lot. And therefore I am referring to your implementation

I was also trying to write a C++ implementation  ([here](https://github.com/Mayankm96/SOFT_odom)), but it is far from completion. We could discuss any specific queries you have regarding the paper over here if you'd like. Also, you could probably check the [viso2_ros](http://wiki.ros.org/viso2_ros) package in case you are looking for just implementing visual odometry.

I hope that helps!
